/// ICAO 9303 country/nationality codes as they appear in an MRZ, resolved to a
/// display name and (where one exists) an ISO 3166-1 alpha-2 code used to build
/// the flag emoji.
class Country {
  const Country(this.name, [this.alpha2]);

  final String name;
  final String? alpha2;

  /// Regional-indicator pair for [alpha2], or `null` for codes that have no
  /// flag (UN travel documents, stateless/refugee codes, …).
  String? get flag {
    final code = alpha2;
    if (code == null || code.length != 2) return null;
    const base = 0x1F1E6; // 🇦
    return String.fromCharCodes(
      code.toUpperCase().codeUnits.map((c) => base + (c - 0x41)),
    );
  }
}

/// Looks up an MRZ country code. Returns `null` for codes we don't know, so
/// callers can fall back to showing the raw code.
Country? lookupCountry(String code) => _countries[code.toUpperCase().trim()];

const _countries = <String, Country>{
  // ISO 3166-1 alpha-3.
  'ABW': Country('Aruba', 'AW'),
  'AFG': Country('Afghanistan', 'AF'),
  'AGO': Country('Angola', 'AO'),
  'AIA': Country('Anguilla', 'AI'),
  'ALA': Country('Åland Islands', 'AX'),
  'ALB': Country('Albania', 'AL'),
  'AND': Country('Andorra', 'AD'),
  'ARE': Country('United Arab Emirates', 'AE'),
  'ARG': Country('Argentina', 'AR'),
  'ARM': Country('Armenia', 'AM'),
  'ASM': Country('American Samoa', 'AS'),
  'ATA': Country('Antarctica', 'AQ'),
  'ATF': Country('French Southern Territories', 'TF'),
  'ATG': Country('Antigua and Barbuda', 'AG'),
  'AUS': Country('Australia', 'AU'),
  'AUT': Country('Austria', 'AT'),
  'AZE': Country('Azerbaijan', 'AZ'),
  'BDI': Country('Burundi', 'BI'),
  'BEL': Country('Belgium', 'BE'),
  'BEN': Country('Benin', 'BJ'),
  'BES': Country('Bonaire, Sint Eustatius and Saba', 'BQ'),
  'BFA': Country('Burkina Faso', 'BF'),
  'BGD': Country('Bangladesh', 'BD'),
  'BGR': Country('Bulgaria', 'BG'),
  'BHR': Country('Bahrain', 'BH'),
  'BHS': Country('Bahamas', 'BS'),
  'BIH': Country('Bosnia and Herzegovina', 'BA'),
  'BLM': Country('Saint Barthélemy', 'BL'),
  'BLR': Country('Belarus', 'BY'),
  'BLZ': Country('Belize', 'BZ'),
  'BMU': Country('Bermuda', 'BM'),
  'BOL': Country('Bolivia', 'BO'),
  'BRA': Country('Brazil', 'BR'),
  'BRB': Country('Barbados', 'BB'),
  'BRN': Country('Brunei Darussalam', 'BN'),
  'BTN': Country('Bhutan', 'BT'),
  'BVT': Country('Bouvet Island', 'BV'),
  'BWA': Country('Botswana', 'BW'),
  'CAF': Country('Central African Republic', 'CF'),
  'CAN': Country('Canada', 'CA'),
  'CCK': Country('Cocos (Keeling) Islands', 'CC'),
  'CHE': Country('Switzerland', 'CH'),
  'CHL': Country('Chile', 'CL'),
  'CHN': Country('China', 'CN'),
  'CIV': Country("Côte d'Ivoire", 'CI'),
  'CMR': Country('Cameroon', 'CM'),
  'COD': Country('Congo (Democratic Republic)', 'CD'),
  'COG': Country('Congo', 'CG'),
  'COK': Country('Cook Islands', 'CK'),
  'COL': Country('Colombia', 'CO'),
  'COM': Country('Comoros', 'KM'),
  'CPV': Country('Cabo Verde', 'CV'),
  'CRI': Country('Costa Rica', 'CR'),
  'CUB': Country('Cuba', 'CU'),
  'CUW': Country('Curaçao', 'CW'),
  'CXR': Country('Christmas Island', 'CX'),
  'CYM': Country('Cayman Islands', 'KY'),
  'CYP': Country('Cyprus', 'CY'),
  'CZE': Country('Czechia', 'CZ'),
  'DEU': Country('Germany', 'DE'),
  'DJI': Country('Djibouti', 'DJ'),
  'DMA': Country('Dominica', 'DM'),
  'DNK': Country('Denmark', 'DK'),
  'DOM': Country('Dominican Republic', 'DO'),
  'DZA': Country('Algeria', 'DZ'),
  'ECU': Country('Ecuador', 'EC'),
  'EGY': Country('Egypt', 'EG'),
  'ERI': Country('Eritrea', 'ER'),
  'ESH': Country('Western Sahara', 'EH'),
  'ESP': Country('Spain', 'ES'),
  'EST': Country('Estonia', 'EE'),
  'ETH': Country('Ethiopia', 'ET'),
  'FIN': Country('Finland', 'FI'),
  'FJI': Country('Fiji', 'FJ'),
  'FLK': Country('Falkland Islands', 'FK'),
  'FRA': Country('France', 'FR'),
  'FRO': Country('Faroe Islands', 'FO'),
  'FSM': Country('Micronesia', 'FM'),
  'GAB': Country('Gabon', 'GA'),
  'GBR': Country('United Kingdom', 'GB'),
  'GEO': Country('Georgia', 'GE'),
  'GGY': Country('Guernsey', 'GG'),
  'GHA': Country('Ghana', 'GH'),
  'GIB': Country('Gibraltar', 'GI'),
  'GIN': Country('Guinea', 'GN'),
  'GLP': Country('Guadeloupe', 'GP'),
  'GMB': Country('Gambia', 'GM'),
  'GNB': Country('Guinea-Bissau', 'GW'),
  'GNQ': Country('Equatorial Guinea', 'GQ'),
  'GRC': Country('Greece', 'GR'),
  'GRD': Country('Grenada', 'GD'),
  'GRL': Country('Greenland', 'GL'),
  'GTM': Country('Guatemala', 'GT'),
  'GUF': Country('French Guiana', 'GF'),
  'GUM': Country('Guam', 'GU'),
  'GUY': Country('Guyana', 'GY'),
  'HKG': Country('Hong Kong', 'HK'),
  'HMD': Country('Heard Island and McDonald Islands', 'HM'),
  'HND': Country('Honduras', 'HN'),
  'HRV': Country('Croatia', 'HR'),
  'HTI': Country('Haiti', 'HT'),
  'HUN': Country('Hungary', 'HU'),
  'IDN': Country('Indonesia', 'ID'),
  'IMN': Country('Isle of Man', 'IM'),
  'IND': Country('India', 'IN'),
  'IOT': Country('British Indian Ocean Territory', 'IO'),
  'IRL': Country('Ireland', 'IE'),
  'IRN': Country('Iran', 'IR'),
  'IRQ': Country('Iraq', 'IQ'),
  'ISL': Country('Iceland', 'IS'),
  'ISR': Country('Israel', 'IL'),
  'ITA': Country('Italy', 'IT'),
  'JAM': Country('Jamaica', 'JM'),
  'JEY': Country('Jersey', 'JE'),
  'JOR': Country('Jordan', 'JO'),
  'JPN': Country('Japan', 'JP'),
  'KAZ': Country('Kazakhstan', 'KZ'),
  'KEN': Country('Kenya', 'KE'),
  'KGZ': Country('Kyrgyzstan', 'KG'),
  'KHM': Country('Cambodia', 'KH'),
  'KIR': Country('Kiribati', 'KI'),
  'KNA': Country('Saint Kitts and Nevis', 'KN'),
  'KOR': Country('Korea (Republic of)', 'KR'),
  'KWT': Country('Kuwait', 'KW'),
  'LAO': Country("Lao People's Democratic Republic", 'LA'),
  'LBN': Country('Lebanon', 'LB'),
  'LBR': Country('Liberia', 'LR'),
  'LBY': Country('Libya', 'LY'),
  'LCA': Country('Saint Lucia', 'LC'),
  'LIE': Country('Liechtenstein', 'LI'),
  'LKA': Country('Sri Lanka', 'LK'),
  'LSO': Country('Lesotho', 'LS'),
  'LTU': Country('Lithuania', 'LT'),
  'LUX': Country('Luxembourg', 'LU'),
  'LVA': Country('Latvia', 'LV'),
  'MAC': Country('Macao', 'MO'),
  'MAF': Country('Saint Martin (French part)', 'MF'),
  'MAR': Country('Morocco', 'MA'),
  'MCO': Country('Monaco', 'MC'),
  'MDA': Country('Moldova', 'MD'),
  'MDG': Country('Madagascar', 'MG'),
  'MDV': Country('Maldives', 'MV'),
  'MEX': Country('Mexico', 'MX'),
  'MHL': Country('Marshall Islands', 'MH'),
  'MKD': Country('North Macedonia', 'MK'),
  'MLI': Country('Mali', 'ML'),
  'MLT': Country('Malta', 'MT'),
  'MMR': Country('Myanmar', 'MM'),
  'MNE': Country('Montenegro', 'ME'),
  'MNG': Country('Mongolia', 'MN'),
  'MNP': Country('Northern Mariana Islands', 'MP'),
  'MOZ': Country('Mozambique', 'MZ'),
  'MRT': Country('Mauritania', 'MR'),
  'MSR': Country('Montserrat', 'MS'),
  'MTQ': Country('Martinique', 'MQ'),
  'MUS': Country('Mauritius', 'MU'),
  'MWI': Country('Malawi', 'MW'),
  'MYS': Country('Malaysia', 'MY'),
  'MYT': Country('Mayotte', 'YT'),
  'NAM': Country('Namibia', 'NA'),
  'NCL': Country('New Caledonia', 'NC'),
  'NER': Country('Niger', 'NE'),
  'NFK': Country('Norfolk Island', 'NF'),
  'NGA': Country('Nigeria', 'NG'),
  'NIC': Country('Nicaragua', 'NI'),
  'NIU': Country('Niue', 'NU'),
  'NLD': Country('Netherlands', 'NL'),
  'NOR': Country('Norway', 'NO'),
  'NPL': Country('Nepal', 'NP'),
  'NRU': Country('Nauru', 'NR'),
  'NZL': Country('New Zealand', 'NZ'),
  'OMN': Country('Oman', 'OM'),
  'PAK': Country('Pakistan', 'PK'),
  'PAN': Country('Panama', 'PA'),
  'PCN': Country('Pitcairn', 'PN'),
  'PER': Country('Peru', 'PE'),
  'PHL': Country('Philippines', 'PH'),
  'PLW': Country('Palau', 'PW'),
  'PNG': Country('Papua New Guinea', 'PG'),
  'POL': Country('Poland', 'PL'),
  'PRI': Country('Puerto Rico', 'PR'),
  'PRK': Country("Korea (Democratic People's Republic of)", 'KP'),
  'PRT': Country('Portugal', 'PT'),
  'PRY': Country('Paraguay', 'PY'),
  'PSE': Country('Palestine', 'PS'),
  'PYF': Country('French Polynesia', 'PF'),
  'QAT': Country('Qatar', 'QA'),
  'REU': Country('Réunion', 'RE'),
  'ROU': Country('Romania', 'RO'),
  'RUS': Country('Russian Federation', 'RU'),
  'RWA': Country('Rwanda', 'RW'),
  'SAU': Country('Saudi Arabia', 'SA'),
  'SDN': Country('Sudan', 'SD'),
  'SEN': Country('Senegal', 'SN'),
  'SGP': Country('Singapore', 'SG'),
  'SGS': Country('South Georgia and the South Sandwich Islands', 'GS'),
  'SHN': Country('Saint Helena', 'SH'),
  'SJM': Country('Svalbard and Jan Mayen', 'SJ'),
  'SLB': Country('Solomon Islands', 'SB'),
  'SLE': Country('Sierra Leone', 'SL'),
  'SLV': Country('El Salvador', 'SV'),
  'SMR': Country('San Marino', 'SM'),
  'SOM': Country('Somalia', 'SO'),
  'SPM': Country('Saint Pierre and Miquelon', 'PM'),
  'SRB': Country('Serbia', 'RS'),
  'SSD': Country('South Sudan', 'SS'),
  'STP': Country('Sao Tome and Principe', 'ST'),
  'SUR': Country('Suriname', 'SR'),
  'SVK': Country('Slovakia', 'SK'),
  'SVN': Country('Slovenia', 'SI'),
  'SWE': Country('Sweden', 'SE'),
  'SWZ': Country('Eswatini', 'SZ'),
  'SXM': Country('Sint Maarten (Dutch part)', 'SX'),
  'SYC': Country('Seychelles', 'SC'),
  'SYR': Country('Syrian Arab Republic', 'SY'),
  'TCA': Country('Turks and Caicos Islands', 'TC'),
  'TCD': Country('Chad', 'TD'),
  'TGO': Country('Togo', 'TG'),
  'THA': Country('Thailand', 'TH'),
  'TJK': Country('Tajikistan', 'TJ'),
  'TKL': Country('Tokelau', 'TK'),
  'TKM': Country('Turkmenistan', 'TM'),
  'TLS': Country('Timor-Leste', 'TL'),
  'TON': Country('Tonga', 'TO'),
  'TTO': Country('Trinidad and Tobago', 'TT'),
  'TUN': Country('Tunisia', 'TN'),
  'TUR': Country('Türkiye', 'TR'),
  'TUV': Country('Tuvalu', 'TV'),
  'TWN': Country('Taiwan', 'TW'),
  'TZA': Country('Tanzania', 'TZ'),
  'UGA': Country('Uganda', 'UG'),
  'UKR': Country('Ukraine', 'UA'),
  'UMI': Country('United States Minor Outlying Islands', 'UM'),
  'URY': Country('Uruguay', 'UY'),
  'USA': Country('United States of America', 'US'),
  'UZB': Country('Uzbekistan', 'UZ'),
  'VAT': Country('Holy See', 'VA'),
  'VCT': Country('Saint Vincent and the Grenadines', 'VC'),
  'VEN': Country('Venezuela', 'VE'),
  'VGB': Country('Virgin Islands (British)', 'VG'),
  'VIR': Country('Virgin Islands (U.S.)', 'VI'),
  'VNM': Country('Viet Nam', 'VN'),
  'VUT': Country('Vanuatu', 'VU'),
  'WLF': Country('Wallis and Futuna', 'WF'),
  'WSM': Country('Samoa', 'WS'),
  'YEM': Country('Yemen', 'YE'),
  'ZAF': Country('South Africa', 'ZA'),
  'ZMB': Country('Zambia', 'ZM'),
  'ZWE': Country('Zimbabwe', 'ZW'),

  // ICAO-specific codes that are not ISO 3166-1 alpha-3.
  'D': Country('Germany', 'DE'),
  'EUE': Country('European Union'),
  'GBD': Country('British Overseas Territories Citizen', 'GB'),
  'GBN': Country('British National (Overseas)', 'GB'),
  'GBO': Country('British Overseas Citizen', 'GB'),
  'GBP': Country('British Protected Person', 'GB'),
  'GBS': Country('British Subject', 'GB'),
  'RKS': Country('Kosovo'),
  'UNA': Country('United Nations specialized agency'),
  'UNK': Country('UNMIK travel document'),
  'UNO': Country('United Nations Organization'),
  'XBA': Country('African Development Bank'),
  'XIM': Country('African Export–Import Bank'),
  'XOM': Country('Sovereign Military Order of Malta'),
  'XXA': Country('Stateless person'),
  'XXB': Country('Refugee (1951 Convention)'),
  'XXC': Country('Refugee (other)'),
  'XXX': Country('Unspecified nationality'),
};
